// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const MESSAGE_TYPES: typeof import('/vercel/share/v0-project/src/utils/messaging').MESSAGE_TYPES
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const animateClick: typeof import('/vercel/share/v0-project/src/utils/animated-cursor').animateClick
  const animateCursorToElement: typeof import('/vercel/share/v0-project/src/utils/animated-cursor').animateCursorToElement
  const animateInput: typeof import('/vercel/share/v0-project/src/utils/animated-cursor').animateInput
  const browser: typeof import('wxt/browser').browser
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createPulseAnimation: typeof import('/vercel/share/v0-project/src/utils/animated-cursor').createPulseAnimation
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const createStepOverlay: typeof import('/vercel/share/v0-project/src/utils/dom-highlighter').createStepOverlay
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const extractPageContext: typeof import('/vercel/share/v0-project/src/utils/page-context').extractPageContext
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const findElementBySelector: typeof import('/vercel/share/v0-project/src/utils/dom-highlighter').findElementBySelector
  const findElementByText: typeof import('/vercel/share/v0-project/src/utils/dom-highlighter').findElementByText
  const generateSessionId: typeof import('/vercel/share/v0-project/src/utils/messaging').generateSessionId
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const getChromeStorageData: typeof import('/vercel/share/v0-project/src/utils/messaging').getChromeStorageData
  const getElementBySelectorHint: typeof import('/vercel/share/v0-project/src/utils/page-context').getElementBySelectorHint
  const highlightElement: typeof import('/vercel/share/v0-project/src/utils/dom-highlighter').highlightElement
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const listenToMessages: typeof import('/vercel/share/v0-project/src/utils/messaging').listenToMessages
  const sanitizePageContext: typeof import('/vercel/share/v0-project/src/utils/page-context').sanitizePageContext
  const sendMessageToBackground: typeof import('/vercel/share/v0-project/src/utils/messaging').sendMessageToBackground
  const setChromeStorageData: typeof import('/vercel/share/v0-project/src/utils/messaging').setChromeStorageData
  const setupContentScript: typeof import('/vercel/share/v0-project/src/utils/content-script-setup').setupContentScript
  const smoothScrollToElement: typeof import('/vercel/share/v0-project/src/utils/dom-highlighter').smoothScrollToElement
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { CursorAnimationOptions } from '/vercel/share/v0-project/src/utils/animated-cursor'
  import('/vercel/share/v0-project/src/utils/animated-cursor')
  // @ts-ignore
  export type { HighlightOptions } from '/vercel/share/v0-project/src/utils/dom-highlighter'
  import('/vercel/share/v0-project/src/utils/dom-highlighter')
}
