// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/apple-icon.png"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icon-dark-32x32.png"
    | "/icon-light-32x32.png"
    | "/icon.svg"
    | "/placeholder-logo.png"
    | "/placeholder-logo.svg"
    | "/placeholder-user.jpg"
    | "/placeholder.jpg"
    | "/placeholder.svg"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
